/**
 * Application error codes and their meanings
 * Centralized error code management for consistent error handling
 */

export const ERROR_CODES = {
  // Authentication errors (AUTH_*)
  AUTH_INVALID_CREDENTIALS: 'AUTH_001',
  AUTH_TOKEN_EXPIRED: 'AUTH_002',
  AUTH_TOKEN_INVALID: 'AUTH_003',
  AUTH_TOKEN_MISSING: 'AUTH_004',
  AUTH_INSUFFICIENT_PERMISSIONS: 'AUTH_005',
  AUTH_ACCOUNT_LOCKED: 'AUTH_006',
  AUTH_ACCOUNT_DISABLED: 'AUTH_007',
  AUTH_MFA_REQUIRED: 'AUTH_008',
  AUTH_MFA_INVALID: 'AUTH_009',
  AUTH_SESSION_EXPIRED: 'AUTH_010',
  
  // Validation errors (VALIDATION_*)
  VALIDATION_REQUIRED_FIELD: 'VALIDATION_001',
  VALIDATION_INVALID_FORMAT: 'VALIDATION_002',
  VALIDATION_OUT_OF_RANGE: 'VALIDATION_003',
  VALIDATION_TOO_LONG: 'VALIDATION_004',
  VALIDATION_TOO_SHORT: 'VALIDATION_005',
  VALIDATION_INVALID_EMAIL: 'VALIDATION_006',
  VALIDATION_INVALID_PHONE: 'VALIDATION_007',
  VALIDATION_INVALID_URL: 'VALIDATION_008',
  VALIDATION_INVALID_DATE: 'VALIDATION_009',
  VALIDATION_INVALID_NUMBER: 'VALIDATION_010',
  
  // Business logic errors (BUSINESS_*)
  BUSINESS_APPOINTMENT_CONFLICT: 'BUSINESS_001',
  BUSINESS_APPOINTMENT_NOT_FOUND: 'BUSINESS_002',
  BUSINESS_APPOINTMENT_CANCELLED: 'BUSINESS_003',
  BUSINESS_LEAD_NOT_FOUND: 'BUSINESS_004',
  BUSINESS_LEAD_ALREADY_EXISTS: 'BUSINESS_005',
  BUSINESS_CAMPAIGN_NOT_FOUND: 'BUSINESS_006',
  BUSINESS_CAMPAIGN_INACTIVE: 'BUSINESS_007',
  BUSINESS_QUOTA_EXCEEDED: 'BUSINESS_008',
  BUSINESS_FEATURE_DISABLED: 'BUSINESS_009',
  BUSINESS_OPERATION_NOT_ALLOWED: 'BUSINESS_010',
  
  // External service errors (EXTERNAL_*)
  EXTERNAL_API_UNAVAILABLE: 'EXTERNAL_001',
  EXTERNAL_API_TIMEOUT: 'EXTERNAL_002',
  EXTERNAL_API_RATE_LIMITED: 'EXTERNAL_003',
  EXTERNAL_API_INVALID_RESPONSE: 'EXTERNAL_004',
  EXTERNAL_API_AUTHENTICATION_FAILED: 'EXTERNAL_005',
  EXTERNAL_DATABASE_CONNECTION_FAILED: 'EXTERNAL_006',
  EXTERNAL_DATABASE_QUERY_FAILED: 'EXTERNAL_007',
  EXTERNAL_EMAIL_SERVICE_FAILED: 'EXTERNAL_008',
  EXTERNAL_SMS_SERVICE_FAILED: 'EXTERNAL_009',
  EXTERNAL_VOICE_SERVICE_FAILED: 'EXTERNAL_010',
  
  // System errors (SYSTEM_*)
  SYSTEM_INTERNAL_ERROR: 'SYSTEM_001',
  SYSTEM_DATABASE_ERROR: 'SYSTEM_002',
  SYSTEM_CACHE_ERROR: 'SYSTEM_003',
  SYSTEM_FILE_SYSTEM_ERROR: 'SYSTEM_004',
  SYSTEM_NETWORK_ERROR: 'SYSTEM_005',
  SYSTEM_MEMORY_ERROR: 'SYSTEM_006',
  SYSTEM_CPU_ERROR: 'SYSTEM_007',
  SYSTEM_DISK_ERROR: 'SYSTEM_008',
  SYSTEM_CONFIGURATION_ERROR: 'SYSTEM_009',
  SYSTEM_DEPENDENCY_ERROR: 'SYSTEM_010',
  
  // Security errors (SECURITY_*)
  SECURITY_CSRF_TOKEN_INVALID: 'SECURITY_001',
  SECURITY_CSRF_TOKEN_MISSING: 'SECURITY_002',
  SECURITY_RATE_LIMIT_EXCEEDED: 'SECURITY_003',
  SECURITY_SUSPICIOUS_ACTIVITY: 'SECURITY_004',
  SECURITY_IP_BLOCKED: 'SECURITY_005',
  SECURITY_USER_AGENT_BLOCKED: 'SECURITY_006',
  SECURITY_INVALID_ORIGIN: 'SECURITY_007',
  SECURITY_MALICIOUS_INPUT: 'SECURITY_008',
  SECURITY_SQL_INJECTION_ATTEMPT: 'SECURITY_009',
  SECURITY_XSS_ATTEMPT: 'SECURITY_010',
  
  // Resource errors (RESOURCE_*)
  RESOURCE_NOT_FOUND: 'RESOURCE_001',
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_002',
  RESOURCE_CONFLICT: 'RESOURCE_003',
  RESOURCE_LOCKED: 'RESOURCE_004',
  RESOURCE_DELETED: 'RESOURCE_005',
  RESOURCE_ACCESS_DENIED: 'RESOURCE_006',
  RESOURCE_QUOTA_EXCEEDED: 'RESOURCE_007',
  RESOURCE_SIZE_EXCEEDED: 'RESOURCE_008',
  RESOURCE_FORMAT_UNSUPPORTED: 'RESOURCE_009',
  RESOURCE_CORRUPTED: 'RESOURCE_010',
  
  // Payment errors (PAYMENT_*)
  PAYMENT_CARD_DECLINED: 'PAYMENT_001',
  PAYMENT_INSUFFICIENT_FUNDS: 'PAYMENT_002',
  PAYMENT_INVALID_CARD: 'PAYMENT_003',
  PAYMENT_EXPIRED_CARD: 'PAYMENT_004',
  PAYMENT_PROCESSING_FAILED: 'PAYMENT_005',
  PAYMENT_REFUND_FAILED: 'PAYMENT_006',
  PAYMENT_WEBHOOK_INVALID: 'PAYMENT_007',
  PAYMENT_SUBSCRIPTION_CANCELLED: 'PAYMENT_008',
  PAYMENT_SUBSCRIPTION_EXPIRED: 'PAYMENT_009',
  PAYMENT_BILLING_ADDRESS_INVALID: 'PAYMENT_010',
} as const;

export const ERROR_MESSAGES = {
  [ERROR_CODES.AUTH_INVALID_CREDENTIALS]: 'Invalid email or password',
  [ERROR_CODES.AUTH_TOKEN_EXPIRED]: 'Authentication token has expired',
  [ERROR_CODES.AUTH_TOKEN_INVALID]: 'Invalid authentication token',
  [ERROR_CODES.AUTH_TOKEN_MISSING]: 'Authentication token is required',
  [ERROR_CODES.AUTH_INSUFFICIENT_PERMISSIONS]: 'Insufficient permissions to perform this action',
  [ERROR_CODES.AUTH_ACCOUNT_LOCKED]: 'Account has been locked due to multiple failed login attempts',
  [ERROR_CODES.AUTH_ACCOUNT_DISABLED]: 'Account has been disabled',
  [ERROR_CODES.AUTH_MFA_REQUIRED]: 'Multi-factor authentication is required',
  [ERROR_CODES.AUTH_MFA_INVALID]: 'Invalid multi-factor authentication code',
  [ERROR_CODES.AUTH_SESSION_EXPIRED]: 'Session has expired, please log in again',
  
  [ERROR_CODES.VALIDATION_REQUIRED_FIELD]: 'This field is required',
  [ERROR_CODES.VALIDATION_INVALID_FORMAT]: 'Invalid format for this field',
  [ERROR_CODES.VALIDATION_OUT_OF_RANGE]: 'Value is out of allowed range',
  [ERROR_CODES.VALIDATION_TOO_LONG]: 'Value is too long',
  [ERROR_CODES.VALIDATION_TOO_SHORT]: 'Value is too short',
  [ERROR_CODES.VALIDATION_INVALID_EMAIL]: 'Invalid email address format',
  [ERROR_CODES.VALIDATION_INVALID_PHONE]: 'Invalid phone number format',
  [ERROR_CODES.VALIDATION_INVALID_URL]: 'Invalid URL format',
  [ERROR_CODES.VALIDATION_INVALID_DATE]: 'Invalid date format',
  [ERROR_CODES.VALIDATION_INVALID_NUMBER]: 'Invalid number format',
  
  [ERROR_CODES.BUSINESS_APPOINTMENT_CONFLICT]: 'Appointment time conflicts with existing appointment',
  [ERROR_CODES.BUSINESS_APPOINTMENT_NOT_FOUND]: 'Appointment not found',
  [ERROR_CODES.BUSINESS_APPOINTMENT_CANCELLED]: 'Appointment has been cancelled',
  [ERROR_CODES.BUSINESS_LEAD_NOT_FOUND]: 'Lead not found',
  [ERROR_CODES.BUSINESS_LEAD_ALREADY_EXISTS]: 'Lead already exists',
  [ERROR_CODES.BUSINESS_CAMPAIGN_NOT_FOUND]: 'Campaign not found',
  [ERROR_CODES.BUSINESS_CAMPAIGN_INACTIVE]: 'Campaign is inactive',
  [ERROR_CODES.BUSINESS_QUOTA_EXCEEDED]: 'Quota exceeded for this operation',
  [ERROR_CODES.BUSINESS_FEATURE_DISABLED]: 'This feature is currently disabled',
  [ERROR_CODES.BUSINESS_OPERATION_NOT_ALLOWED]: 'This operation is not allowed',
  
  [ERROR_CODES.EXTERNAL_API_UNAVAILABLE]: 'External service is currently unavailable',
  [ERROR_CODES.EXTERNAL_API_TIMEOUT]: 'External service request timed out',
  [ERROR_CODES.EXTERNAL_API_RATE_LIMITED]: 'External service rate limit exceeded',
  [ERROR_CODES.EXTERNAL_API_INVALID_RESPONSE]: 'Invalid response from external service',
  [ERROR_CODES.EXTERNAL_API_AUTHENTICATION_FAILED]: 'External service authentication failed',
  [ERROR_CODES.EXTERNAL_DATABASE_CONNECTION_FAILED]: 'Database connection failed',
  [ERROR_CODES.EXTERNAL_DATABASE_QUERY_FAILED]: 'Database query failed',
  [ERROR_CODES.EXTERNAL_EMAIL_SERVICE_FAILED]: 'Email service failed',
  [ERROR_CODES.EXTERNAL_SMS_SERVICE_FAILED]: 'SMS service failed',
  [ERROR_CODES.EXTERNAL_VOICE_SERVICE_FAILED]: 'Voice service failed',
  
  [ERROR_CODES.SYSTEM_INTERNAL_ERROR]: 'An internal error occurred',
  [ERROR_CODES.SYSTEM_DATABASE_ERROR]: 'Database error occurred',
  [ERROR_CODES.SYSTEM_CACHE_ERROR]: 'Cache error occurred',
  [ERROR_CODES.SYSTEM_FILE_SYSTEM_ERROR]: 'File system error occurred',
  [ERROR_CODES.SYSTEM_NETWORK_ERROR]: 'Network error occurred',
  [ERROR_CODES.SYSTEM_MEMORY_ERROR]: 'Memory error occurred',
  [ERROR_CODES.SYSTEM_CPU_ERROR]: 'CPU error occurred',
  [ERROR_CODES.SYSTEM_DISK_ERROR]: 'Disk error occurred',
  [ERROR_CODES.SYSTEM_CONFIGURATION_ERROR]: 'Configuration error occurred',
  [ERROR_CODES.SYSTEM_DEPENDENCY_ERROR]: 'Dependency error occurred',
  
  [ERROR_CODES.SECURITY_CSRF_TOKEN_INVALID]: 'Invalid CSRF token',
  [ERROR_CODES.SECURITY_CSRF_TOKEN_MISSING]: 'CSRF token is missing',
  [ERROR_CODES.SECURITY_RATE_LIMIT_EXCEEDED]: 'Rate limit exceeded',
  [ERROR_CODES.SECURITY_SUSPICIOUS_ACTIVITY]: 'Suspicious activity detected',
  [ERROR_CODES.SECURITY_IP_BLOCKED]: 'IP address is blocked',
  [ERROR_CODES.SECURITY_USER_AGENT_BLOCKED]: 'User agent is blocked',
  [ERROR_CODES.SECURITY_INVALID_ORIGIN]: 'Invalid origin',
  [ERROR_CODES.SECURITY_MALICIOUS_INPUT]: 'Malicious input detected',
  [ERROR_CODES.SECURITY_SQL_INJECTION_ATTEMPT]: 'SQL injection attempt detected',
  [ERROR_CODES.SECURITY_XSS_ATTEMPT]: 'XSS attempt detected',
  
  [ERROR_CODES.RESOURCE_NOT_FOUND]: 'Resource not found',
  [ERROR_CODES.RESOURCE_ALREADY_EXISTS]: 'Resource already exists',
  [ERROR_CODES.RESOURCE_CONFLICT]: 'Resource conflict',
  [ERROR_CODES.RESOURCE_LOCKED]: 'Resource is locked',
  [ERROR_CODES.RESOURCE_DELETED]: 'Resource has been deleted',
  [ERROR_CODES.RESOURCE_ACCESS_DENIED]: 'Access to resource denied',
  [ERROR_CODES.RESOURCE_QUOTA_EXCEEDED]: 'Resource quota exceeded',
  [ERROR_CODES.RESOURCE_SIZE_EXCEEDED]: 'Resource size exceeded',
  [ERROR_CODES.RESOURCE_FORMAT_UNSUPPORTED]: 'Resource format not supported',
  [ERROR_CODES.RESOURCE_CORRUPTED]: 'Resource is corrupted',
  
  [ERROR_CODES.PAYMENT_CARD_DECLINED]: 'Payment card was declined',
  [ERROR_CODES.PAYMENT_INSUFFICIENT_FUNDS]: 'Insufficient funds',
  [ERROR_CODES.PAYMENT_INVALID_CARD]: 'Invalid payment card',
  [ERROR_CODES.PAYMENT_EXPIRED_CARD]: 'Payment card has expired',
  [ERROR_CODES.PAYMENT_PROCESSING_FAILED]: 'Payment processing failed',
  [ERROR_CODES.PAYMENT_REFUND_FAILED]: 'Refund processing failed',
  [ERROR_CODES.PAYMENT_WEBHOOK_INVALID]: 'Invalid payment webhook',
  [ERROR_CODES.PAYMENT_SUBSCRIPTION_CANCELLED]: 'Subscription has been cancelled',
  [ERROR_CODES.PAYMENT_SUBSCRIPTION_EXPIRED]: 'Subscription has expired',
  [ERROR_CODES.PAYMENT_BILLING_ADDRESS_INVALID]: 'Invalid billing address',
} as const;

export const ERROR_CATEGORIES = {
  AUTHENTICATION: 'AUTH_',
  VALIDATION: 'VALIDATION_',
  BUSINESS: 'BUSINESS_',
  EXTERNAL: 'EXTERNAL_',
  SYSTEM: 'SYSTEM_',
  SECURITY: 'SECURITY_',
  RESOURCE: 'RESOURCE_',
  PAYMENT: 'PAYMENT_',
} as const;










