import type { Metadata, Viewport } from 'next'
import { JetBrains_Mono, Space_Grotesk } from 'next/font/google'
import './globals.css'
import { ToastProvider } from './contexts/ToastContext'
import { RealtimeProvider } from './contexts/RealtimeProvider'
import { DashboardDataProvider } from './contexts/DashboardDataContext'
import { ErrorBoundary } from './components/ErrorBoundary'
import * as Sentry from '@sentry/nextjs'

if (process.env.NEXT_PUBLIC_SENTRY_DSN) {
 Sentry.init({
 dsn: process.env.NEXT_PUBLIC_SENTRY_DSN,
 environment: process.env.NODE_ENV,
 tracesSampleRate: 0.1
 })
}

const mono = JetBrains_Mono({
 subsets: ['latin'],
 weight: ['400', '500'],
 variable: '--font-mono',
})

const display = Space_Grotesk({
 subsets: ['latin'],
 weight: ['400', '500', '600', '700'],
 variable: '--font-display',
})

export const metadata: Metadata = {
 metadataBase: new URL('https://cloudgreet.com'),
 title: 'CloudGreet - 24/7 AI Receptionist for Service Businesses',
 description: 'CloudGreet is a 24/7 AI receptionist for service businesses. It answers every call, books jobs straight into your calendar, texts customers back, and logs every transcript and recording in your dashboard. Built for HVAC, plumbing, electrical, roofing, painting, contractors, and any business that lives on the phone.',
 keywords: 'AI receptionist, AI voice assistant, virtual receptionist, answering service, appointment scheduling, call answering, missed call text back, HVAC, plumbing, electrical, roofing, painting, contractors, service business automation',
 authors: [{ name: 'CloudGreet Team' }],
 creator: 'CloudGreet',
 publisher: 'CloudGreet',
 // Favicon + apple-touch icon are auto-detected from app/icon.png and
 // app/apple-icon.png by Next.js — no need to declare them here.
 openGraph: {
 // Social share image is generated by app/opengraph-image.tsx (Next.js
 // file convention auto-injects it), so no images array is declared here.
 title: 'CloudGreet - Never Miss A Call Again',
 description: 'A 24/7 AI receptionist for service businesses. Answers every call, books jobs into your calendar, and texts customers back.',
 url: 'https://cloudgreet.com',
 siteName: 'CloudGreet',
 locale: 'en_US',
 type: 'website',
 },
 twitter: {
 // Image comes from app/twitter-image.tsx (file convention).
 card: 'summary_large_image',
 title: 'CloudGreet - Never Miss A Call Again',
 description: 'A 24/7 AI receptionist for service businesses.',
 },
 formatDetection: {
 email: false,
 address: false,
 telephone: false,
 },
 alternates: {
 canonical: '/',
 },
 robots: {
 index: true,
 follow: true,
 googleBot: {
 index: true,
 follow: true,
 'max-video-preview': -1,
 'max-image-preview': 'large',
 'max-snippet': -1,
 },
 },
 verification: {
 google: process.env.NEXT_PUBLIC_GOOGLE_VERIFICATION_CODE || '',
 },
}

export const viewport: Viewport = {
 width: 'device-width',
 initialScale: 1,
 maximumScale: 1,
 themeColor: '#0f172a',
}

export default function RootLayout({
 children,
}: {
 children: React.ReactNode
}) {
 const orgJsonLd = {
 '@context': 'https://schema.org',
 '@type': 'Organization',
 name: 'CloudGreet',
 url: 'https://cloudgreet.com',
 logo: 'https://cloudgreet.com/cloudgreet-logo.png',
 description:
  'CloudGreet is a 24/7 AI receptionist for service businesses. It answers every call, books jobs into your calendar, and texts customers back.',
 contactPoint: {
  '@type': 'ContactPoint',
  telephone: '+1-737-937-0084',
  contactType: 'sales',
  areaServed: 'US',
  availableLanguage: ['English', 'Spanish'],
 },
 }

 const softwareJsonLd = {
 '@context': 'https://schema.org',
 '@type': 'SoftwareApplication',
 name: 'CloudGreet',
 applicationCategory: 'BusinessApplication',
 operatingSystem: 'Web',
 url: 'https://cloudgreet.com',
 description:
  'A 24/7 AI receptionist for service businesses. Answers calls, books appointments straight into your calendar, handles texts, and logs every transcript and recording in your dashboard.',
 provider: { '@type': 'Organization', name: 'CloudGreet', url: 'https://cloudgreet.com' },
 }

 return (
 <html lang="en" className="overscroll-none">
 <head>
 <link rel="manifest" href="/manifest.json" />
 {/* Premium type for the demo-agents carousel (Fontshare, free for commercial). */}
 <link rel="preconnect" href="https://api.fontshare.com" crossOrigin="" />
 <link rel="stylesheet" href="https://api.fontshare.com/v2/css?f[]=clash-display@500,600,700&f[]=general-sans@400,500,600&display=swap" />
 <script
 type="application/ld+json"
 dangerouslySetInnerHTML={{ __html: JSON.stringify(orgJsonLd) }}
 />
 <script
 type="application/ld+json"
 dangerouslySetInnerHTML={{ __html: JSON.stringify(softwareJsonLd) }}
 />
 <meta name="mobile-web-app-capable" content="yes" />
 <meta name="apple-mobile-web-app-capable" content="yes" />
 <meta name="apple-mobile-web-app-status-bar-style" content="default" />
 <meta name="apple-mobile-web-app-title" content="CloudGreet" />
 {/* Unregister any service worker that earlier builds installed; the
     pass-through SW added no value and was holding stale assets that
     showed up on iOS as a black rectangle below the nav. */}
 <script
 dangerouslySetInnerHTML={{
 __html: `
 if ('serviceWorker' in navigator) {
 navigator.serviceWorker.getRegistrations().then(function (regs) {
  regs.forEach(function (r) { r.unregister(); });
 });
 if (window.caches && caches.keys) {
  caches.keys().then(function (keys) {
   keys.forEach(function (k) { caches.delete(k); });
  });
 }
 }
 `,
 }}
 />
 </head>
 <body className={`${mono.variable} ${display.variable} font-sans overscroll-none bg-[#f6f5f1] text-gray-900 antialiased`}>
 <ErrorBoundary>
 <ToastProvider>
 <RealtimeProvider>
 <DashboardDataProvider>
 {children}
 </DashboardDataProvider>
 </RealtimeProvider>
 </ToastProvider>
 </ErrorBoundary>
 </body>
 </html>
 )
}
