'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { motion, useReducedMotion } from 'framer-motion'
import { fetchWithAuth } from '@/lib/auth/fetch-with-auth'
import {
  PhoneCall, PhoneIncoming, Target, CaretRight, Coffee, CalendarCheck,
} from '@phosphor-icons/react'
import { NotificationsBell } from '@/components/NotificationsBell'
import {
  NumberTicker, AnimatedCircularProgressBar, MiniBarChart, DualLineChart,
} from '@/app/_shared/magic-ui'
import { firaCode } from './fonts'

/*
 * Design tokens per the v5 spec (scratchpad/setter-design-spec.md):
 * generated by running ui-ux-pro-max's search engine for a B2B SaaS
 * sales-dialer dashboard, validated with the dataviz palette validator
 * (#2563eb, #0891b2, #d97706 vs #ffffff - all checks pass), constrained
 * to CloudGreet brand blue + zero purple + white canvas.
 */
const NAVY = '#1E3A8A'      // heading ink ("Foreground" from the skill engine)
const BLUE = '#2563eb'      // brand primary / series 1
const CYAN = '#0891b2'      // series 2 (connects)
const AMBER = '#D97706'     // accent - weekly goal / bonus ONLY
const DEEMPH = '#C7D7F4'    // de-emphasis marks
const TRACK = '#DBEAFE'     // meter track (lighter step, same ramp)

const EASE = [0.22, 1, 0.36, 1] as const

export type UpNextLead = { id: string; business_name: string | null; phone: string; status: string; due?: boolean }
export type WeeklyGoal = {
  target: number
  /** Demos HELD (client showed) this week - the goal counts show-ups, not bookings. */
  this_week: number
  met_this_week: boolean
  streak_weeks: number
  bonus_earned: boolean
  bonus_amount: number
  streak_target: number
}
export type Overview = {
  calls: {
    today: { attempts: number; connects: number; talk_seconds: number }
    week: { attempts: number; connects: number; talk_seconds: number }
  }
  leads: {
    total: number
    new: number
    interested: number
    dead_or_dnc: number
    demos_booked_today: number
    demos_booked_week: number
  }
  daily: { date: string; dials: number; connects: number; demos: number }[]
  series?: RangeSeries
  up_next: UpNextLead[]
  callbacks_due?: number
  weekly_goal: WeeklyGoal
}

export type ChartRange = 'today' | 'week' | 'all'
export type RangeSeries = {
  range: string
  points: { key: string; dials: number; connects: number; demos: number }[]
  demos_total: number
}

const fmtPhone = (raw: string) => {
  const d = raw.replace(/\D/g, '').replace(/^1/, '')
  if (d.length !== 10) return raw
  return `(${d.slice(0, 3)}) ${d.slice(3, 6)}-${d.slice(6)}`
}

const dayLabel = (iso: string) =>
  new Date(`${iso}T00:00:00Z`).toLocaleDateString(undefined, { weekday: 'short', timeZone: 'UTC' })

const fmtTalk = (s: number) => {
  const m = Math.round(s / 60)
  return m >= 60 ? `${Math.floor(m / 60)}h ${m % 60}m` : `${m}m`
}

/** Quiet bordered period tag ("This week" / "Today"). */
function PeriodTag({ children }: { children: React.ReactNode }) {
  return (
    <span className="text-[11px] font-medium text-slate-500 border border-[#E3EAF4] rounded-md px-2 py-1 whitespace-nowrap">
      {children}
    </span>
  )
}

/** White card shell - hairline border, whisper shadow, 12px radius. */
function Card({ className = '', children }: { className?: string; children: React.ReactNode }) {
  return (
    <div className={`bg-white rounded-xl border border-[#E3EAF4] shadow-[0_1px_2px_rgba(16,24,40,0.04)] ${className}`}>
      {children}
    </div>
  )
}

/**
 * Setter Overview dashboard - pure presentational. The real page feeds it
 * live /api/setter/overview data; the preview route feeds it fixtures so
 * the design can be screenshot-reviewed without auth.
 *
 * Composition follows the Figma reference (hero chart left, stat tiles
 * right, meter + bars + tilted goal card row) on a white canvas.
 */
export function OverviewDashboard({ data, firstName }: { data: Overview; firstName: string | null }) {
  const reduceMotion = useReducedMotion()

  // Hero-chart range: 'week' renders from the data prop; the other two
  // fetch their series on demand (keyed per range, cached in state).
  const [range, setRange] = useState<ChartRange>('week')
  const [seriesByRange, setSeriesByRange] = useState<Partial<Record<ChartRange, RangeSeries>>>({})
  useEffect(() => {
    if (range === 'week' || seriesByRange[range]) return
    let cancelled = false
    void (async () => {
      try {
        const r = await fetchWithAuth(`/api/setter/overview?range=${range}`)
        const j = await r.json().catch(() => ({}))
        if (!cancelled && j?.series) setSeriesByRange((prev) => ({ ...prev, [range]: j.series }))
      } catch { /* keep whatever's shown */ }
    })()
    return () => { cancelled = true }
  }, [range, seriesByRange])

  const weekSeries: RangeSeries = data.series && data.series.range === 'week'
    ? data.series
    : {
        range: 'week',
        points: data.daily.map((d) => ({ key: d.date, dials: d.dials, connects: d.connects, demos: d.demos })),
        demos_total: data.leads.demos_booked_week,
      }
  const activeSeries = range === 'week' ? weekSeries : (seriesByRange[range] || weekSeries)
  const seriesLoading = range !== 'week' && !seriesByRange[range]
  const pointLabel = (key: string) =>
    range === 'today'
      ? new Date(key).toLocaleTimeString(undefined, { hour: 'numeric' })
      : range === 'all'
        ? new Date(`${key}T00:00:00Z`).toLocaleDateString(undefined, { month: 'short', day: 'numeric', timeZone: 'UTC' })
        : dayLabel(key)
  const demosCaption = range === 'today' ? 'Demos booked today' : range === 'all' ? 'Demos booked all-time' : 'Demos booked this week'

  const connectRate =
    data.calls.today.attempts > 0
      ? (data.calls.today.connects / data.calls.today.attempts) * 100
      : 0

  const statusPill: Record<string, string> = {
    new: 'bg-sky-100 text-sky-700',
    interested: 'bg-emerald-100 text-emerald-700',
  }
  const statusLabel: Record<string, string> = { new: 'New', interested: 'Interested' }

  // One orchestrated entrance (stagger + 8px rise), disabled under
  // prefers-reduced-motion. That's the whole motion budget.
  const rise = (i: number) =>
    reduceMotion
      ? {}
      : {
          initial: { opacity: 0, y: 8 },
          animate: { opacity: 1, y: 0 },
          transition: { duration: 0.4, ease: EASE, delay: i * 0.06 },
        }

  return (
    <section className="max-w-7xl mx-auto px-4 sm:px-6 md:px-8 py-8">
      {/* Header */}
      <div className="flex items-start justify-between gap-4 flex-wrap mb-7">
        <div>
          <h1 className="text-3xl md:text-4xl font-semibold tracking-tight leading-tight" style={{ color: NAVY }}>
            {firstName ? `Welcome, ${firstName}!` : 'Welcome!'}
          </h1>
          <p className="text-sm text-slate-500 mt-1">Here&apos;s your setter dashboard for today.</p>
        </div>
        <div className="flex items-center gap-2">
          <Link
            href="/setter/leads/scrape"
            className="inline-flex items-center gap-1.5 text-sm font-medium text-slate-700 bg-white hover:bg-slate-50 border border-[#E3EAF4] rounded-lg px-3.5 py-2.5 transition-colors duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600 focus-visible:ring-offset-2"
          >
            <Target weight="fill" className="w-3.5 h-3.5 text-blue-600" /> Scrape leads
          </Link>
          <Link
            href="/setter/leads"
            className="inline-flex items-center gap-1.5 text-sm font-semibold text-white bg-blue-600 hover:bg-blue-700 rounded-lg px-3.5 py-2.5 shadow-sm transition-colors duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600 focus-visible:ring-offset-2"
          >
            <PhoneCall weight="fill" className="w-3.5 h-3.5" /> Start dialing
          </Link>
          <div className="ml-1 rounded-full bg-white border border-[#E3EAF4] w-10 h-10 flex items-center justify-center">
            <NotificationsBell basePath="/api/sales/notifications" />
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 mb-4">
        {/* Hero: demos-booked figure + dials-vs-connects trend.
            (Dials and connects share a scale; demos does NOT ride this
            axis - scale-mismatch anti-pattern.) */}
        <motion.div {...rise(0)} className="lg:col-span-2">
          <Card className="p-6 h-full">
            <div className="flex items-start justify-between flex-wrap gap-3">
              <div>
                <div className="text-5xl leading-none font-semibold" style={{ color: NAVY }}>
                  <NumberTicker value={activeSeries.demos_total} />
                </div>
                <div className="text-sm font-medium text-blue-600 mt-2">{demosCaption}</div>
              </div>
              <div className="flex items-center gap-4 flex-wrap">
                <span className="inline-flex items-center gap-1.5 text-xs text-slate-500">
                  <span className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: BLUE }} /> Dials
                </span>
                <span className="inline-flex items-center gap-1.5 text-xs text-slate-500">
                  <span className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: CYAN }} /> Connects
                </span>
                <div className="inline-flex rounded-lg border border-[#E3EAF4] bg-white p-0.5">
                  {([['today', 'Today'], ['week', 'This week'], ['all', 'All-time']] as [ChartRange, string][]).map(([value, label]) => (
                    <button
                      key={value}
                      type="button"
                      onClick={() => setRange(value)}
                      className={`text-[11px] font-medium rounded-md px-2.5 py-1 transition-colors duration-150 ${
                        range === value ? 'bg-blue-600 text-white' : 'text-slate-500 hover:text-slate-800'
                      }`}
                    >
                      {label}
                    </button>
                  ))}
                </div>
              </div>
            </div>
            <div className={seriesLoading ? 'opacity-50 transition-opacity' : 'transition-opacity'}>
              <DualLineChart
                labels={activeSeries.points.map((p) => pointLabel(p.key))}
                seriesA={activeSeries.points.map((p) => p.dials)}
                seriesB={activeSeries.points.map((p) => p.connects)}
                colorA={BLUE}
                colorB={CYAN}
                height={190}
                className="mt-5"
              />
            </div>
          </Card>
        </motion.div>

        {/* Stat tiles */}
        <div className="flex flex-col gap-4">
          <motion.div {...rise(1)} className="flex-1">
            <Card className="p-5 h-full flex items-center gap-4">
              <div className="w-12 h-12 rounded-full bg-blue-50 text-blue-600 flex items-center justify-center shrink-0">
                <PhoneCall weight="duotone" className="w-5 h-5" />
              </div>
              <div className="min-w-0 flex-1">
                <div className="text-sm text-slate-500">Dials today</div>
                <div className="text-[28px] leading-tight font-semibold" style={{ color: NAVY }}>
                  <NumberTicker value={data.calls.today.attempts} />
                </div>
              </div>
            </Card>
          </motion.div>
          <motion.div {...rise(2)} className="flex-1">
            <Card className="p-5 h-full flex items-center gap-4">
              <div className="w-12 h-12 rounded-full bg-cyan-50 text-cyan-700 flex items-center justify-center shrink-0">
                <PhoneIncoming weight="duotone" className="w-5 h-5" />
              </div>
              <div className="min-w-0 flex-1">
                <div className="text-sm text-slate-500">Connects today</div>
                <div className="text-[28px] leading-tight font-semibold" style={{ color: NAVY }}>
                  <NumberTicker value={data.calls.today.connects} />
                </div>
              </div>
            </Card>
          </motion.div>
        </div>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 mb-6">
        {/* Connect rate - single ratio, so a meter (not a 2-slice donut);
            counts always visible as text beside it. */}
        <motion.div {...rise(3)}>
          <Card className="p-5 h-full">
            <div className="flex items-center justify-between mb-4">
              <div className="text-sm font-semibold" style={{ color: NAVY }}>Connect rate</div>
              <PeriodTag>Today</PeriodTag>
            </div>
            <div className="flex items-center justify-center gap-6 pt-1">
              <AnimatedCircularProgressBar
                value={connectRate}
                size={124}
                strokeWidth={12}
                gaugePrimaryColor={BLUE}
                gaugeSecondaryColor={TRACK}
              >
                <span className="text-xl font-semibold" style={{ color: NAVY }}>
                  {Math.round(connectRate)}%
                </span>
              </AnimatedCircularProgressBar>
              <div className="space-y-3">
                <div className="flex items-center gap-2">
                  <span className="w-3 h-3 rounded-full shrink-0" style={{ backgroundColor: BLUE }} />
                  <div>
                    <div className="text-[11px] text-slate-500">Connected</div>
                    <div className="text-sm font-semibold text-slate-800">{data.calls.today.connects}</div>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  <span className="w-3 h-3 rounded-full shrink-0" style={{ backgroundColor: DEEMPH }} />
                  <div>
                    <div className="text-[11px] text-slate-500">No answer</div>
                    <div className="text-sm font-semibold text-slate-800">
                      {Math.max(0, data.calls.today.attempts - data.calls.today.connects)}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </Card>
        </motion.div>

        {/* Demos per day - single series, today emphasized. */}
        <motion.div {...rise(4)}>
          <Card className="p-5 h-full">
            <div className="flex items-center justify-between mb-4">
              <div className="text-sm font-semibold" style={{ color: NAVY }}>Demos booked</div>
              <PeriodTag>This week</PeriodTag>
            </div>
            <MiniBarChart
              labels={data.daily.map((d) => dayLabel(d.date))}
              data={data.daily.map((d) => d.demos)}
              color={DEEMPH}
              highlightColor={BLUE}
              height={180}
            />
          </Card>
        </motion.div>

        {/* Weekly goal - THE signature element: the one bold card on the
            white canvas (navy, tilted like the reference's calendar card,
            amber reserved for the money). */}
        <motion.div {...rise(5)} className="sm:col-span-2 lg:col-span-1">
          <div
            className="rounded-xl p-5 h-full flex flex-col -rotate-2 shadow-[0_16px_32px_-12px_rgba(30,58,138,0.45)] text-white"
            style={{ backgroundImage: `linear-gradient(170deg, ${NAVY} 0%, #0B1B3F 100%)` }}
          >
            <div className="flex items-center gap-2 mb-1">
              <CalendarCheck weight="duotone" className="w-5 h-5" style={{ color: '#FBBF24' }} />
              <div className="text-sm font-semibold">Weekly goal</div>
            </div>
            <div className="text-xs text-blue-200/80 mb-5">
              {data.weekly_goal.this_week} of {data.weekly_goal.target} demos held this week
            </div>
            <div className="flex items-center gap-2 mb-4">
              {Array.from({ length: data.weekly_goal.streak_target }).map((_, i) => (
                <div
                  key={i}
                  className={`flex-1 h-11 rounded-lg flex items-center justify-center text-xs font-semibold ${
                    i < data.weekly_goal.streak_weeks ? 'text-white' : 'bg-white/10 text-blue-200/60'
                  }`}
                  style={i < data.weekly_goal.streak_weeks ? { backgroundColor: AMBER } : undefined}
                >
                  Wk {i + 1}
                </div>
              ))}
            </div>
            <div className="text-center text-xs text-blue-200/80 mb-5">
              {data.weekly_goal.bonus_earned ? (
                <span className="font-semibold" style={{ color: '#FBBF24' }}>
                  ${data.weekly_goal.bonus_amount} bonus earned
                </span>
              ) : (
                <>
                  {data.weekly_goal.streak_weeks} of {data.weekly_goal.streak_target} weeks straight,{' '}
                  <span className="font-semibold" style={{ color: '#FBBF24' }}>${data.weekly_goal.bonus_amount} bonus</span>{' '}
                  at {data.weekly_goal.streak_target}
                </>
              )}
            </div>
            <Link
              href="/setter/leads"
              className="mt-auto inline-flex items-center justify-center gap-1.5 bg-white hover:bg-blue-50 text-sm font-semibold rounded-lg px-4 py-2.5 transition-colors duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white focus-visible:ring-offset-2 focus-visible:ring-offset-blue-900"
              style={{ color: NAVY }}
            >
              <PhoneCall weight="fill" className="w-3.5 h-3.5" /> Keep dialing
            </Link>
          </div>
        </motion.div>
      </div>

      {/* Up-next call list + pipeline breakdown */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        <motion.div {...rise(6)} className="lg:col-span-2">
          <Card className="overflow-hidden h-full">
            <div className="px-5 py-4 border-b border-[#EEF2F7] flex items-center justify-between gap-3">
              <div>
                <div className="text-base font-semibold" style={{ color: NAVY }}>Up next</div>
                <div className="text-xs text-slate-500 mt-0.5">Callbacks due first, then oldest untouched</div>
              </div>
              {(data.callbacks_due ?? 0) > 0 && (
                <span className="shrink-0 inline-flex items-center gap-1 text-[11px] font-semibold text-amber-800 bg-amber-50 border border-amber-200 rounded-full px-2.5 py-1">
                  {data.callbacks_due} callback{data.callbacks_due === 1 ? '' : 's'} due
                </span>
              )}
            </div>
            {data.up_next.length === 0 ? (
              <div className="px-5 py-10 text-center">
                <div className="inline-flex items-center justify-center w-10 h-10 rounded-xl bg-slate-100 text-slate-400 mb-3">
                  <Coffee weight="duotone" className="w-5 h-5" />
                </div>
                <p className="text-sm text-slate-700 font-medium">Nothing queued up</p>
                <p className="text-xs text-slate-500 mt-0.5">Scrape a fresh list to start dialing.</p>
              </div>
            ) : (
              <ul className="divide-y divide-[#EEF2F7]">
                {data.up_next.map((lead) => (
                  <li key={lead.id} className="px-5 py-3 flex items-center justify-between gap-3">
                    <div className="flex items-center gap-3 min-w-0">
                      <div className="w-9 h-9 rounded-full bg-blue-50 text-blue-700 flex items-center justify-center text-xs font-semibold uppercase shrink-0">
                        {(lead.business_name || '?').slice(0, 1)}
                      </div>
                      <div className="min-w-0">
                        <div className="text-sm font-medium text-slate-800 truncate">
                          {lead.business_name || 'Unnamed lead'}
                        </div>
                        <div className={`text-xs text-slate-500 whitespace-nowrap ${firaCode.className}`}>{fmtPhone(lead.phone)}</div>
                      </div>
                    </div>
                    <span className={`hidden sm:inline-flex shrink-0 text-[10px] font-medium px-2 py-0.5 rounded-full ${
                      lead.due ? 'bg-amber-100 text-amber-800' : statusPill[lead.status] || 'bg-slate-100 text-slate-600'
                    }`}>
                      {lead.due ? 'Callback due' : statusLabel[lead.status] || lead.status}
                    </span>
                  </li>
                ))}
              </ul>
            )}
          </Card>
        </motion.div>

        <motion.div {...rise(7)}>
          <Card className="overflow-hidden h-full">
            <div className="px-5 py-4 border-b border-[#EEF2F7] flex items-center justify-between gap-3">
              <div>
                <div className="text-base font-semibold" style={{ color: NAVY }}>
                  {data.leads.total === 0 ? 'No leads yet' : 'Your leads'}
                </div>
                {data.leads.total > 0 && (
                  <div className="text-xs text-slate-500 mt-0.5">{data.leads.total} total</div>
                )}
              </div>
              <Link
                href="/setter/leads"
                className="text-xs font-medium text-blue-600 hover:text-blue-700 inline-flex items-center gap-1 shrink-0 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600 rounded"
              >
                Open <CaretRight className="w-3 h-3" />
              </Link>
            </div>
            <ul className="divide-y divide-[#EEF2F7]">
              <li className="px-5 py-3.5 flex items-center justify-between text-sm">
                <span className="text-slate-600">Untouched</span>
                <span className="font-medium tabular-nums text-slate-900">{data.leads.new}</span>
              </li>
              <li className="px-5 py-3.5 flex items-center justify-between text-sm">
                <span className="text-slate-600">Interested</span>
                <span className="font-medium tabular-nums text-emerald-700">{data.leads.interested}</span>
              </li>
              <li className="px-5 py-3.5 flex items-center justify-between text-sm">
                <span className="text-slate-600">Dead / DNC</span>
                <span className="font-medium tabular-nums text-slate-400">{data.leads.dead_or_dnc}</span>
              </li>
              <li className="px-5 py-3.5 flex items-center justify-between text-sm">
                <span className="text-slate-600">Demos booked today</span>
                <span className="font-medium tabular-nums text-slate-900">{data.leads.demos_booked_today}</span>
              </li>
              <li className="px-5 py-3.5 flex items-center justify-between text-sm">
                <span className="text-slate-600">Talk time today</span>
                <span className="font-medium tabular-nums text-slate-900">{fmtTalk(data.calls.today.talk_seconds)}</span>
              </li>
            </ul>
          </Card>
        </motion.div>
      </div>
    </section>
  )
}
