#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run lint-staged
npx lint-staged

# Run type checking
npx tsc --noEmit

# Run security audit
npm audit --audit-level moderate

# Run tests
npm run test:unit